name: CI

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Smoke test
        run: python -c "import app; print('app.py imported successfully')"

  test:
    needs: hello
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest test_app.py -v

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/kudak-03/infra-health-monitor:${{ github.sha }}

  update-gitops:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: Kudak-03/infra-health-gitops
          token: ${{ secrets.GITOPS_PAT_01 }}
          path: gitops

      - name: Update image tag
        run: |
          sed -i "s|image: ghcr.io/kudak-03/infra-health-monitor:.*|image: ghcr.io/kudak-03/infra-health-monitor:${{ github.sha }}|" gitops/deployment.yaml
          cat gitops/deployment.yaml

      - name: Commit and push
        run: |
          cd gitops
          git config user.name "github-actions-bot"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}" || echo "No changes to commit"
          git push
